import React, { useEffect, useMemo, useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import api, { authFetch } from "../api";
import "./Payslip.css";

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

export default function Payslip() {
  const role = localStorage.getItem("role");

  const [employees, setEmployees] = useState([]);
  const [selectedEmployee, setSelectedEmployee] = useState("");

  const [month, setMonth] = useState("");
  const [year, setYear] = useState(new Date().getFullYear());

  const [basicSalary, setBasicSalary] = useState("");
  const [hra, setHra] = useState("");
  const [allowance, setAllowance] = useState("");
  const [deduction, setDeduction] = useState("");

  const [loading, setLoading] = useState(false);
  const [msg, setMsg] = useState("");
  const [err, setErr] = useState("");

  const [payslips, setPayslips] = useState([]);
  const [loadingPayslips, setLoadingPayslips] = useState(false);

  const isAdminOrHr = role === "ADMIN" || role === "HR";
  const isEmployee = role === "EMPLOYEE";

  // ---------------------------
  // Load employees (Admin/HR)
  // ---------------------------
  useEffect(() => {
    const loadEmployees = async () => {
      try {
        const res = await api.get("/api/employees");
        setEmployees(res.data || []);
      } catch (e) {
        console.log(e);
      }
    };

    if (isAdminOrHr) loadEmployees();
  }, [isAdminOrHr]);


  // Separating Month and Year from schema stored data

  const parseMonthYear = (monthYear) => {
    if (!monthYear) return { month: "", year: "" };

    const parts = monthYear.split(" ");
    return {
      month: parts[0],
      year: Number(parts[1]),
    };
  };



  // ---------------------------
  // Load payslips
  // ---------------------------
  const fetchPayslips = async () => {
    setErr("");
    setMsg("");
    setLoadingPayslips(true);

    try {
      // EMPLOYEE -> /me
      if (isEmployee) {
        const data = await authFetch("/api/payslips/me");
        setPayslips(data || []);
      }

      // ADMIN/HR -> if selected employee
      if (isAdminOrHr && selectedEmployee) {
        const data = await authFetch(
          `/api/payslips/${selectedEmployee}`
        );
        setPayslips(data || []);
      }

      if (isAdminOrHr && !selectedEmployee) {
        setPayslips([]);
      }
    } catch (e) {
      setErr(e.message || "Failed to load payslips");
    } finally {
      setLoadingPayslips(false);
    }
  };

  useEffect(() => {
    fetchPayslips();
    // eslint-disable-next-line
  }, [selectedEmployee, role]);

  // ---------------------------
  // Helpers
  // ---------------------------
  const selectedEmpObj = useMemo(() => {
    if (!selectedEmployee) return null;
    return employees.find((e) => e.employeeId === selectedEmployee) || null;
  }, [employees, selectedEmployee]);

  const formatMonthYear = (slip) => {
    if (slip?.month && slip?.year) return `${slip.month} ${slip.year}`;
    if (slip?.monthYear) return slip.monthYear;
    return "-";
  };

  const downloadPayslipPDF = (slip) => {
    const doc = new jsPDF();

    const monthYear = formatMonthYear(slip);

    // backend fields: employeeName
    const name = slip.employeeName || slip.fullName || "-";
    const email = slip.email || "-";
    const employeeId = slip.employeeId || "-";

    const basic = Number(slip.basicSalary || 0);
    const hraVal = Number(slip.hra || 0);
    const allow = Number(slip.allowance || 0);
    const deduct = Number(slip.deduction || 0);

    const totalEarn = Number(slip.totalEarnings || (basic + hraVal + allow));
    const net = Number(slip.netSalary || (totalEarn - deduct));

    doc.setFontSize(18);
    doc.text("HRMS Lite - Payslip", 14, 20);

    doc.setFontSize(12);
    doc.text(`Employee Name: ${name}`, 14, 32);
    doc.text(`Email: ${email}`, 14, 40);
    doc.text(`Employee ID: ${employeeId}`, 14, 48);
    doc.text(`Month: ${monthYear}`, 14, 56);

    autoTable(doc, {
      startY: 65,
      head: [["Earnings", "Amount (₹)"]],
      body: [
        ["Basic Salary", basic],
        ["HRA", hraVal],
        ["Allowance", allow],
        ["Total Earnings", totalEarn],
      ],
    });

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 10,
      head: [["Deductions", "Amount (₹)"]],
      body: [["Deductions", deduct]],
    });

    doc.setFontSize(14);
    doc.text(`Net Salary: ₹${net}`, 14, doc.lastAutoTable.finalY + 25);

    doc.setFontSize(10);
    doc.text(
      `Generated By: ${slip.generatedBy || "-"} | Role: ${slip.generatedRole || "-"}`,
      14,
      doc.lastAutoTable.finalY + 35
    );

    doc.save(`${employeeId}_${monthYear}_payslip.pdf`);
  };

  // ---------------------------
  // Generate Payslip (Admin/HR)
  // ---------------------------
  const handleGeneratePayslip = async () => {
    setErr("");
    setMsg("");

    if (!selectedEmployee || !month || !year) {
      setErr("Please select employee, month, and year.");
      return;
    }

    if (basicSalary === "" || hra === "" || allowance === "" || deduction === "") {
      setErr("Please fill all salary fields.");
      return;
    }

    const payload = {
      employeeId: selectedEmployee,
      month,
      year: Number(year),
      basicSalary: Number(basicSalary),
      hra: Number(hra),
      allowance: Number(allowance),
      deduction: Number(deduction),
    };

    try {
      setLoading(true);

      const res = await authFetch("/api/payslips/generate", {
        method: "POST",
        body: JSON.stringify(payload),
      });

      setMsg(res?.message || "Payslip generated successfully ✅");

      await fetchPayslips();

      setBasicSalary("");
      setHra("");
      setAllowance("");
      setDeduction("");
    } catch (e) {
      setErr(e.message || "Failed to generate payslip");
    } finally {
      setLoading(false);
    }
  };

  // ---------------------------
  // Delete Payslip (Admin/HR)
  // ---------------------------
  const handleDeletePayslip = async (slip) => {
    try {
      setLoading(true);
      setErr("");
      setMsg("");

      const monthYear = slip.monthYear || `${slip.month} ${slip.year}`;
      const { month, year } = parseMonthYear(monthYear);

      if (!month || !year) {
        setErr("Invalid payslip month/year");
        return;
      }

      await authFetch(
        `/api/payslips/${slip.employeeId}/${month}/${year}`,
        {
          method: "DELETE",
        }
      );

      setMsg("Payslip deleted successfully ✅");
      await fetchPayslips();
    } catch (e) {
      setErr(e.message || "Failed to delete payslip");
    } finally {
      setLoading(false);
    }
  };

  // ---------------------------
  // Regenerate Payslip (Admin/HR)
  // ---------------------------
  // const handleRegeneratePayslip = async (slip) => {
  //   try {
  //     setLoading(true);
  //     setErr("");
  //     setMsg("");

  //     const monthYear = slip.monthYear || `${slip.month} ${slip.year}`;
  //     const { month, year } = parseMonthYear(monthYear);

  //     await authFetch("/api/payslips/regenerate", {
  //       method: "POST",
  //       body: JSON.stringify({
  //         employeeId: slip.employeeId,
  //         month,
  //         year,
  //         basicSalary: slip.basicSalary,
  //         hra: slip.hra,
  //         allowance: slip.allowance,
  //         deduction: slip.deduction,
  //       }),
  //     });

  //     setMsg("Payslip regenerated successfully ✅");
  //     await fetchPayslips();
  //   } catch (e) {
  //     setErr(e.message || "Failed to regenerate payslip");
  //   } finally {
  //     setLoading(false);
  //   }
  // };

  // ===========================
  // UI
  // ===========================
  return (
    <div className="ps-page">
      <div className="ps-card">
        <h3 className="ps-title">Payslips</h3>

        {/* ADMIN/HR FORM */}
        {isAdminOrHr && (
          <>
            <h4 className="ps-subtitle">Generate Payslip (Admin/HR)</h4>

            <div className="ps-grid ps-grid-3">
              <select
                className="ps-input"
                value={selectedEmployee}
                onChange={(e) => setSelectedEmployee(e.target.value)}
                disabled={loading}
              >
                <option value="">Select Employee</option>
                {employees.map((emp) => (
                  <option key={emp.employeeId} value={emp.employeeId}>
                    {emp.fullName} ({emp.employeeId})
                  </option>
                ))}
              </select>

              <select
                className="ps-input"
                value={month}
                onChange={(e) => setMonth(e.target.value)}
                disabled={loading}
              >
                <option value="">Select Month</option>
                {MONTHS.map((m) => (
                  <option key={m} value={m}>
                    {m}
                  </option>
                ))}
              </select>

              <input
                className="ps-input"
                type="number"
                value={year}
                onChange={(e) => setYear(e.target.value)}
                placeholder="Year"
                disabled={loading}
              />
            </div>

            <div className="ps-divider" />

            <h4 className="ps-subtitle">Salary Details</h4>

            <div className="ps-grid ps-grid-4">
              <input
                className="ps-input"
                type="number"
                value={basicSalary}
                onChange={(e) => setBasicSalary(e.target.value)}
                placeholder="Basic Salary"
                disabled={loading}
              />

              <input
                className="ps-input"
                type="number"
                value={hra}
                onChange={(e) => setHra(e.target.value)}
                placeholder="HRA"
                disabled={loading}
              />

              <input
                className="ps-input"
                type="number"
                value={allowance}
                onChange={(e) => setAllowance(e.target.value)}
                placeholder="Allowance"
                disabled={loading}
              />

              <input
                className="ps-input"
                type="number"
                value={deduction}
                onChange={(e) => setDeduction(e.target.value)}
                placeholder="Deductions"
                disabled={loading}
              />
            </div>

            <button
              className="ps-btn"
              onClick={handleGeneratePayslip}
              disabled={loading}
            >
              {loading ? "Generating..." : "Generate Payslip (Save to DB)"}
            </button>
          </>
        )}

        {/* Messages */}
        {err && <p className="ps-error">{err}</p>}
        {msg && <p className="ps-success">{msg}</p>}

        <div className="ps-divider" />

        {/* Payslips List */}
        <h4 className="ps-subtitle">
          {isEmployee ? "My Payslips" : "Generated Payslips"}
        </h4>

        {loadingPayslips ? (
          <p>Loading payslips...</p>
        ) : payslips.length === 0 ? (
          <p className="ps-note">
            {isEmployee
              ? "No payslips generated for you yet."
              : selectedEmployee
                ? "No payslips generated for this employee."
                : "Select an employee to view generated payslips."}
          </p>
        ) : (
          <div className="ps-list">
            {payslips.map((slip, idx) => (
              <div className="ps-item" key={`${slip.employeeId}-${slip.month}-${slip.year}-${idx}`}>
                <div>
                  <div className="ps-item-title">
                    {formatMonthYear(slip)} — ₹{slip.netSalary}
                  </div>

                  <div className="ps-item-sub">
                    {(slip.employeeName || slip.fullName)} ({slip.employeeId})
                  </div>
                </div>

                <div className="ps-actions">
                  <button
                    className="ps-btn small"
                    onClick={() => downloadPayslipPDF(slip)}
                  >
                    Download
                  </button>

                  {/* ADMIN/HR actions */}
                  {isAdminOrHr && (
                    <>
                      {/* <button
                        className="ps-btn small"
                        onClick={() => handleRegeneratePayslip(slip)}
                      >
                        Regenerate
                      </button> */}

                      <button
                        className="ps-btn small danger"
                        onClick={() => handleDeletePayslip(slip)}
                      >
                        Delete
                      </button>
                    </>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
